baseURL         = "https://dojoconsortium.org/"
description     = "Dojo Consortium Playbooks"
enableRobotsTXT = true
title           = "Dojo Consortium"

enableGitInfo = true

pygmentsCodeFences = true
pygmentsStyle      = "tango"
pygmentsUseClasses = false
pygmentsUseClassic = false

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = [
    "HTML",
    "RSS",
    "print"
  ]

[imaging]
  anchor         = "smart"
  quality        = 75
  resampleFilter = "CatmullRom"

[[module.mounts]]
  source = "content/en"
  target = "content"

[languages.en]
  languageName = "English"

  [languages.en.params]
    description = "Dojo Consortium Playbooks"
    title       = "Dojo Consortium"

[markup.goldmark.parser.attribute]
  block = true

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "tango"

[taxonomies]
  category = "categories"
  tag      = "tags"

[params.taxonomy]
  # set taxonomyCloud = [] to hide taxonomy clouds
  taxonomyCloud = [
    "categories",
    "tags"
  ]

  # If used, must have same lang as taxonomyCloud
  taxonomyCloudTitle = [
    "Categories",
    "Tag Cloud"
  ]

  # set taxonomyPageHeader = [] to hide taxonomies on the page headers
  taxonomyPageHeader = [
    "categories",
    "tags"
  ]

# Configure how URLs look like per section.
[permalinks]
  blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
  angledQuotes    = false
  hrefTargetBlank = true
  latexDashes     = true
  plainIDAnchors  = true

[services]
  [services.googleAnalytics]
    # Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
    #id = "UA-00000000-0"

    # Language configuration

    # Everything below this are Site Params

[params]
  archived_version          = false
  copyright                 = "Licensed Creative Commons 4.0"
  github_branch             = "main"
  github_repo               = "https://github.com/devopsdojoconsortium/dojoconsortium.org"
  license                   = "https://creativecommons.org/licenses/by/4.0/"
  offlineSearch             = true
  prism_syntax_highlighting = true
  version                   = "1.0"
  version_menu              = "Releases"

  [params.ui]
    breadcrumb_disable                    = false
    footer_about_disable                  = false
    navbar_logo                           = false
    navbar_translucent_over_cover_disable = true
    sidebar_menu_compact                  = false
    sidebar_search_disable                = true
    [params.ui.feedback]
      enable = false
      no     = 'Sorry to hear that. Please <a href="https://github.com/devopsdojoconsortium/dojoconsortium.org/issues/new">tell us how we can improve</a>.'
      yes    = 'Glad to hear it! Please <a href="https://github.com/devopsdojoconsortium/dojoconsortium.org/issues/new">tell us how we can improve</a>.'

    [params.ui.readingtime]
      enable = true

[params.links]
  [[params.links.developer]]
    desc = "Content suggestions welcome!"
    icon = "fab fa-github"
    name = "GitHub"
    url  = "https://github.com/devopsdojoconsortium/dojoconsortium.org"

[module]
  proxy = "direct"
  [module.hugoVersion]
    extended = true
    min      = "0.73.0"
  [[module.imports]]
    disable = false
    path    = "github.com/google/docsy"
