[build]
    command = "hugo"
    publish = "public"

    [build.environment]
        GO_VERSION   = "1.23.0"
        HUGO_VERSION = "v0.151.2"
        NODE_VERSION = "24"

[[redirects]]
    force  = true
    from   = "/"
    status = 301
    to     = "/docs/"
